version: '3'
services:
  ml_template:
    build:
      context: .
    env_file: .env
    tty: true
    stdin_open: true
    shm_size: '25G'
    ports:
      - 8888:8888
    volumes:
      - ./src:/app/src
      - ./data:/app/data
      - ./models:/app/models
      - ./docs:/app/docs
      - ./notebooks:/app/notebooks
      - ./bin:/app/bin
      - ./meta:/app/meta
    entrypoint: ["sh","bin/jupyter_run.sh"]
